//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JetFrames.AppleJobs.Editor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Grid01LayoutX {
            get {
                return ((double)(this["Grid01LayoutX"]));
            }
            set {
                this["Grid01LayoutX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Grid01LayoutY {
            get {
                return ((double)(this["Grid01LayoutY"]));
            }
            set {
                this["Grid01LayoutY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NaN")]
        public double Grid01LayoutWidth {
            get {
                return ((double)(this["Grid01LayoutWidth"]));
            }
            set {
                this["Grid01LayoutWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NaN")]
        public double Grid01LayoutHeight {
            get {
                return ((double)(this["Grid01LayoutHeight"]));
            }
            set {
                this["Grid01LayoutHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double Grid02LayoutX {
            get {
                return ((double)(this["Grid02LayoutX"]));
            }
            set {
                this["Grid02LayoutX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double Grid03LayoutX {
            get {
                return ((double)(this["Grid03LayoutX"]));
            }
            set {
                this["Grid03LayoutX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public double Grid04LayoutX {
            get {
                return ((double)(this["Grid04LayoutX"]));
            }
            set {
                this["Grid04LayoutX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double Grid02LayoutY {
            get {
                return ((double)(this["Grid02LayoutY"]));
            }
            set {
                this["Grid02LayoutY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double Grid03LayoutY {
            get {
                return ((double)(this["Grid03LayoutY"]));
            }
            set {
                this["Grid03LayoutY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public double Grid04LayoutY {
            get {
                return ((double)(this["Grid04LayoutY"]));
            }
            set {
                this["Grid04LayoutY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NaN")]
        public double Grid02LayoutWidth {
            get {
                return ((double)(this["Grid02LayoutWidth"]));
            }
            set {
                this["Grid02LayoutWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NaN")]
        public double Grid03LayoutWidth {
            get {
                return ((double)(this["Grid03LayoutWidth"]));
            }
            set {
                this["Grid03LayoutWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NaN")]
        public double Grid04LayoutWidth {
            get {
                return ((double)(this["Grid04LayoutWidth"]));
            }
            set {
                this["Grid04LayoutWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NaN")]
        public double Grid02LayoutHeight {
            get {
                return ((double)(this["Grid02LayoutHeight"]));
            }
            set {
                this["Grid02LayoutHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NaN")]
        public double Grid03LayoutHeight {
            get {
                return ((double)(this["Grid03LayoutHeight"]));
            }
            set {
                this["Grid03LayoutHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NaN")]
        public double Grid04LayoutHeight {
            get {
                return ((double)(this["Grid04LayoutHeight"]));
            }
            set {
                this["Grid04LayoutHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Grid01Expanded {
            get {
                return ((bool)(this["Grid01Expanded"]));
            }
            set {
                this["Grid01Expanded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Grid02Expanded {
            get {
                return ((bool)(this["Grid02Expanded"]));
            }
            set {
                this["Grid02Expanded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Grid03Expanded {
            get {
                return ((bool)(this["Grid03Expanded"]));
            }
            set {
                this["Grid03Expanded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Grid04Expanded {
            get {
                return ((bool)(this["Grid04Expanded"]));
            }
            set {
                this["Grid04Expanded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ZoomPadX {
            get {
                return ((double)(this["ZoomPadX"]));
            }
            set {
                this["ZoomPadX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ZoomPadY {
            get {
                return ((double)(this["ZoomPadY"]));
            }
            set {
                this["ZoomPadY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double Zoom {
            get {
                return ((double)(this["Zoom"]));
            }
            set {
                this["Zoom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Grid05Expanded {
            get {
                return ((bool)(this["Grid05Expanded"]));
            }
            set {
                this["Grid05Expanded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public double Grid05LayoutX {
            get {
                return ((double)(this["Grid05LayoutX"]));
            }
            set {
                this["Grid05LayoutX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Grid05LayoutY {
            get {
                return ((double)(this["Grid05LayoutY"]));
            }
            set {
                this["Grid05LayoutY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NaN")]
        public double Grid05LayoutWidth {
            get {
                return ((double)(this["Grid05LayoutWidth"]));
            }
            set {
                this["Grid05LayoutWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NaN")]
        public double Grid05LayoutHeight {
            get {
                return ((double)(this["Grid05LayoutHeight"]));
            }
            set {
                this["Grid05LayoutHeight"] = value;
            }
        }
    }
}
